import Head from 'next/head'
import ToggleTheme from 'components/ToggleTheme'
import favicon from '../../public/favicon.ico'
import styled from 'styled-components'

const RootContainer = styled.div`
  min-height: 100vh;
  min-width: 300px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 30px;
  padding: 0 20%;
`

type Props = {
  children: React.ReactNode | undefined
}

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Jason F. Zou</title>
        <meta name="description" content="Generated by Jason Zou" />
        <meta name="color-scheme" content="light dark" />
        <link rel="icon" href={favicon.src} type="image/x-icon" />
      </Head>
      <RootContainer id="#root">
        <nav>Navbar</nav>
        <ToggleTheme />
        <main>{children}</main>
        <footer>Footer</footer>
      </RootContainer>
    </>
  )
}
